### ISSUE TITLE
Can't mass-assign protected attributes: variant_ids_string

### ISSUE THREAD

**Issue by thoughtpunch** [iloveitaly/spree_promo_variant_rule#1]
Looks passing back the variant_ids is throwing protected attribute errors

**Comment by iloveitaly** [comment]
Could you give me more context? How did you trigger this error?

**Comment by thoughtpunch** [comment]
@iloveitaly sorry, I mean to give more context.

Basically "variant_ids_string" is not an accessible attribute of Spree::PromotionRule. I added an `attr_accessible` entry for `variant_ids_string` and it works fine. 

Just wanted to give you a heads up

**Comment by iloveitaly** [comment]
Great, thanks for the info! When I upgrade this extension I'll definitely keep that in mind.

Feel free to open a PR if you've already fixed the issue or have made other improvements! Thanks!
